name: CI

on:
    push:
        branches:
            - master
    pull_request:

env:
    DEFAULT_COMPOSER_FLAGS: --no-interaction --no-ansi --no-progress --no-suggest

jobs:

    test:

        name: Test

        strategy:
            matrix:
                # php-version:
                #     - 7.1
                #     - 7.2
                #     - 7.3
                #     - 7.4
                dependencies:
                    - low
                    - high
        steps:
            - uses: actions/checkout@v2

            - run: Show PHP info
              run: php -v

            - name: Validate Composer
              run: composer validate

            - name: Install dependencies
              run: |
                  if [[ "$DEPENDENCIES" = 'high' ]]; then composer update $DEFAULT_COMPOSER_FLAGS; fi
                  if [[ "$DEPENDENCIES" = 'low' ]]; then composer update $DEFAULT_COMPOSER_FLAGS --prefer-lowest; fi


            - name: PHPUnit
              run: composer phpunit

            - name: PHPStan
              run: composer phpstan

            - name: PHPCS
              run: composer phpcs
